### ISSUE TITLE
Erreur sur webpack lors de l'installation du portail

### ISSUE THREAD

**Issue by r0one** [simde-utc/portail#229]
`git clone`, `docker-compose up`, `docker logs portail_nodejs_1`:
```
> @ watch /var/www/html
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/webpack/bin/webpack.js ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-14T13_23_41_252Z-debug.log
```

**Comment by r0one** [comment]
On a une erreur similaire avec un `composer install` puis `portail install` :
```
1/9 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  11% [Portail Install] Préparation
 [Portail Install] Préparation - Portail
  1/14 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   7% /!\ Le fichier .env existe déjà /!\ 

 Le remplacer (ancienne version déplacée en .env.last) ? (yes/no) [no]:
 > 

 2/9 [▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░]  22% [Portail Install] Installation des dépendances Composer
sh: 1: composer: not found
 3/9 [▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░]  33% [Portail Install] Définition des clés
Application key [base64:qWSbmcqbydBYsM4CmGp/xXScjHkexwnzXuhrDFrXcAY=] set successfully.
Encryption keys already exist. Use the --force option to overwrite them.
 4/9 [▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░]  44% [Portail Install] Installation des dépendances NodeJS
npm WARN @babel/plugin-syntax-jsx@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-react-display-name@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-react-jsx@7.3.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-react-jsx-self@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-react-jsx-source@7.2.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/preset-react@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-dom@15.6.1 requires a peer of react@^15.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/.staging/fsevents-858f4cf3/node_modules/mkdirp/node_modules/abbrev' -> '/home/romain/Documents/dev/portail/node_modules/.staging/abbrev-f0d0812f'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules/fsevents/node_modules/core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/core-util-is' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules/fsevents/node_modules/delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/delegates' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules/fsevents/node_modules/fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/fs.realpath' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules/fsevents/node_modules/has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/has-unicode' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules/fsevents/node_modules/mkdirp/node_modules/aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/aproba' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.aproba.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules/fsevents/node_modules/mkdirp/node_modules/balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/balanced-match' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules/fsevents/node_modules/mkdirp/node_modules/concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/concat-map' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: brace-expansion@1.1.11 (node_modules/fsevents/node_modules/mkdirp/node_modules/brace-expansion):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/brace-expansion' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.brace-expansion.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules/fsevents/node_modules/mkdirp/node_modules/console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/console-control-strings' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules/fsevents/node_modules/mkdirp/node_modules/delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/delegates' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules/fsevents/node_modules/mkdirp/node_modules/fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/fs.realpath' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules/fsevents/node_modules/mkdirp/node_modules/has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/has-unicode' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.3 (node_modules/fsevents/node_modules/mkdirp/node_modules/inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/inherits' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimatch@3.0.4 (node_modules/fsevents/node_modules/mkdirp/node_modules/minimatch):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/minimatch' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.minimatch.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: glob@7.1.3 (node_modules/fsevents/node_modules/glob):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/glob' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/.glob.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inflight@1.0.6 (node_modules/fsevents/node_modules/mkdirp/node_modules/inflight):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/inflight' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.inflight.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: debug@2.6.9 (node_modules/fsevents/node_modules/debug):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/debug' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/.debug.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.6.0 (node_modules/fsevents/node_modules/deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/deep-extend' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules/fsevents/node_modules/detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/detect-libc' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-minipass@1.2.5 (node_modules/fsevents/node_modules/fs-minipass):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/fs-minipass' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/.fs-minipass.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gauge@2.7.4 (node_modules/fsevents/node_modules/gauge):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/gauge' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/.gauge.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mkdirp@0.5.1 (node_modules/fsevents/node_modules/mkdirp):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/.staging/mkdirp-a4835faf' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules/fsevents/node_modules/mkdirp/node_modules/abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/abbrev' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules/fsevents/node_modules/mkdirp/node_modules/ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/ansi-regex' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.0.1 (node_modules/fsevents/node_modules/mkdirp/node_modules/chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/chownr' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.chownr.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules/fsevents/node_modules/mkdirp/node_modules/code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/code-point-at' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules/fsevents/node_modules/mkdirp/node_modules/core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/core-util-is' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: debug@2.6.9 (node_modules/fsevents/node_modules/mkdirp/node_modules/debug):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/debug' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.debug.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.5.1 (node_modules/fsevents/node_modules/mkdirp/node_modules/deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/deep-extend' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules/fsevents/node_modules/mkdirp/node_modules/detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/detect-libc' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-minipass@1.2.5 (node_modules/fsevents/node_modules/mkdirp/node_modules/fs-minipass):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/fs-minipass' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.fs-minipass.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gauge@2.7.4 (node_modules/fsevents/node_modules/mkdirp/node_modules/gauge):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/gauge' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.gauge.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: glob@7.1.2 (node_modules/fsevents/node_modules/mkdirp/node_modules/glob):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/glob' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.glob.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: iconv-lite@0.4.21 (node_modules/fsevents/node_modules/mkdirp/node_modules/iconv-lite):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/iconv-lite' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.iconv-lite.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ignore-walk@3.0.1 (node_modules/fsevents/node_modules/mkdirp/node_modules/ignore-walk):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/ignore-walk' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.ignore-walk.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules/fsevents/node_modules/mkdirp/node_modules/ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/ini' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.ini.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: is-fullwidth-code-point@1.0.0 (node_modules/fsevents/node_modules/mkdirp/node_modules/is-fullwidth-code-point):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/is-fullwidth-code-point' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.is-fullwidth-code-point.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules/fsevents/node_modules/mkdirp/node_modules/isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/isarray' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.isarray.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.0 (node_modules/fsevents/node_modules/mkdirp/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/minimist' -> '/home/romain/Documents/dev/portail/node_modules/fsevents/node_modules/mkdirp/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/react-datetime-range-picker/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

sh: 1: cross-env: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/romain/.npm/_logs/2019-06-14T13_50_58_380Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/romain/.npm/_logs/2019-06-14T13_50_58_392Z-debug.log
 5/9 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░]  55% [Portail Install] Migration
```
Visiblement c'est pas la faute de docker, mais celle de webpack.

**Comment by r0one** [comment]
Le `.env` que j'ai utilisé pour l'installation sans docker:
```
APP_NAME="Portail des Assos"
APP_ENV=develop
APP_KEY=base64:qWSbmcqbydBYsM4CmGp/xXScjHkexwnzXuhrDFrXcAY=
APP_DEBUG=true
APP_URL=http://localhost:8000
APP_ASSO=simde

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=portail
DB_USERNAME=portail
DB_PASSWORD=portail

OLD_DB_CONNECTION=mysql
OLD_DB_HOST=127.0.0.1
OLD_DB_PORT=3306
OLD_DB_DATABASE=portail-old
OLD_DB_USERNAME=portail-old
OLD_DB_PASSWORD=portail-old

BROADCAST_DRIVER=log
CACHE_DRIVER=redis
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=database

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

CAS_URL=
CAS_IMAGE=

GINGER_KEY=
```

**Comment by NastuzziSamy** [comment]
@CdRom1  tu es bien sur develop ?
+ tu peux me donner ton package-lock ? + as tu des changements git durant ton installl ?

**Comment by lvaroqui** [comment]
J'ai la même erreur sur develop @NastuzziSamy, voilà mon [package-lock](https://github.com/simde-utc/portail/files/3551580/package-lock.zip).

J'ai dû remplacer _mysql-client_ par _mariadb-client_ dans le app.dockerfile pour réussir à build le container php. Voir [erreur sur stackoverflow](https://stackoverflow.com/questions/57048428/e-package-mysql-client-has-no-installation-candidate-in-php-fpm-image-build-u).

**Comment by lvaroqui** [comment]
Par contre en utilisant directement composer et php artisan j'ai aucun problème

**Comment by Minigugus** [comment]
C'est juste que `cross-env` est supposé installé par défaut, ce qui est généralement le cas si on l'utilise pas docker. Or il n'était pas installé dans les containers avec l'ancienne configuration 

> ```
> sh: 1: cross-env: not found
> ```

Cette issue sera donc réglé quand #278 sera merge :wink:
https://github.com/simde-utc/portail/blob/711da7b37af4d04cc0137c993e71afdbf594b99e/docker/configurations/front/Dockerfile#L4
